name: huyphan
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Điều chỉnh phù hợp với Flutter và Dart SDK đang sử dụng.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8 # Sử dụng các biểu tượng theo phong cách Cupertino cho iOS.
  dio: ^5.8.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true # Sử dụng Material Icons.

  assets:
    - C:\dart\huyphan\picture.png # Đảm bảo đường dẫn hình ảnh chính xác.